# This is a workflow to keep CoachEdge Streamlit Apps active
name: commit_scheduler

on:
  schedule:
    # 6:00 AM CT (12:00 UTC)
    - cron: '0 12 * * *'
    # 3:00 PM CT (21:00 UTC)
    - cron: '0 21 * * *'
    # 11:00 PM CT (05:00 UTC)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push commit
        run: |
          python ./.github/workflows/file_editor.py
          git config --global user.email "jacktwoods01@gmail.com"
          git config --global user.name "jtw0086"
          git add coachedge_non_spiritual.py
          git add coachedge_spiritual.py
          git add coachaidge4_0.py
          git add coachedge_coach.py
          git add sb_step1.py
          git commit -m "Scheduled-Commit"  git push
